// data/data.js
export const rows = [
    { id: 1, name: 'Alice', rating: 3.5, country: 'USA', dateCreated: '2023-09-01', isAdmin: true, sabuk: "hijau", provinsi: "jateng" },
    { id: 2, name: 'Bob', rating: 2.0, country: 'Canada', dateCreated: '2023-08-15', isAdmin: false, sabuk: "hijau", provinsi: "jateng" },
    { id: 3, name: 'Charlie', rating: 4.7, country: 'UK', dateCreated: '2023-07-22', isAdmin: true, sabuk: "hijau", provinsi: "jateng" },
    { id: 4, name: 'David', rating: 1.8, country: 'Germany', dateCreated: '2023-04-20', isAdmin: false, sabuk: "hitam", provinsi: "jatim" },
    { id: 5, name: 'Eva', rating: 3.2, country: 'France', dateCreated: '2010-03-30', isAdmin: false, sabuk: "hijau", provinsi: "jatim" },
    { id: 7, name: 'budi', rating: 3.2, country: 'France', dateCreated: '2011-02-03', isAdmin: false, sabuk: "biru", provinsi: "jatim" },
    { id: 8, name: 'pop', rating: 3.2, country: 'France', dateCreated: '2013-05-06', isAdmin: false, sabuk: "hijau", provinsi: "jatim" },
    { id: 9, name: 'edang', rating: 3.2, country: 'inggris', dateCreated: '2016-02-09', isAdmin: false, sabuk: "hijau", provinsi: "jatim" },
    { id: 10, name: 'luna', rating: 3.2, country: 'indonesia', dateCreated: '2012-04-03', isAdmin: false, sabuk: "hijau", provinsi: "aceh" },
    { id: 11, name: 'ling', rating: 3.2, country: 'brazil', dateCreated: '2015-09-03', isAdmin: false, sabuk: "hijau", provinsi: "aceh" },
    { id: 12, name: 'balmond', rating: 3.2, country: 'argentina', dateCreated: '2001-03-03', isAdmin: false, sabuk: "hitam", provinsi: "jateng" },
    { id: 13, name: 'layla', rating: 3.2, country: 'France', dateCreated: '2018-02-03', isAdmin: false, sabuk: "hijau", provinsi: "jatim" },
    { id: 14, name: 'alucard', rating: 3.2, country: 'argentina', dateCreated: '2019-02-03', isAdmin: true, sabuk: "hijau", provinsi: "kaltim" },
    { id: 15, name: 'fanny', rating: 3.2, country: 'singapure', dateCreated: '2012-02-03', isAdmin: false, sabuk: "hijau", provinsi: "jatim" },
    { id: 16, name: 'funny', rating: 3.2, country: 'argentina', dateCreated: '2017-02-03', isAdmin: false, sabuk: "merah", provinsi: "jatim" },
    { id: 17, name: 'rudi', rating: 3.2, country: 'singapure', dateCreated: '2014-02-03', isAdmin: false, sabuk: "merah", provinsi: "kalmtim" },
    { id: 18, name: 'rudas', rating: 3.2, country: 'malaysia', dateCreated: '2014-02-03', isAdmin: false, sabuk: "hijau", provinsi: "jatim" },
    { id: 19, name: 'kolil', rating: 3.2, country: 'singapure', dateCreated: '2018-02-03', isAdmin: true, sabuk: "hijau", provinsi: "kaltim" },
    { id: 20, name: 'joko', rating: 3.2, country: 'malaysia', dateCreated: '2001-02-03', isAdmin: false, sabuk: "kuning", provinsi: "jatim" },
    { id: 21, name: 'bal', rating: 3.2, country: 'malaysia', dateCreated: '2002-02-03', isAdmin: true, sabuk: "kuning", provinsi: "jatim" },
    { id: 22, name: 'ani', rating: 3.2, country: 'vietnam', dateCreated: '2006-02-03', isAdmin: true, sabuk: "hijau", provinsi: "ntt" },
    { id: 23, name: 'eren', rating: 3.2, country: 'vietnam', dateCreated: '2008-02-03', isAdmin: false, sabuk: "testing", provinsi: "kalse" },
    { id: 24, name: 'mikasa', rating: 3.2, country: 'juanda', dateCreated: '2019-02-03', isAdmin: false, sabuk: "abu", provinsi: "sumsel" },
    { id: 25, name: 'levy', rating: 3.2, country: 'juanda', dateCreated: '2006-02-03', isAdmin: true, sabuk: "coklat", provinsi: "sumsel" },
    { id: 26, name: 'armin', rating: 3.2, country: 'japang', dateCreated: '2091-02-03', isAdmin: false, sabuk: "coklat", provinsi: "ntb" },
    { id: 27, name: 'berthold', rating: 3.2, country: 'France', dateCreated: '2018-02-03', isAdmin: true, sabuk: "merah", provinsi: "bali" },
    { id: 28, name: 'reinar', rating: 3.2, country: 'vietnam', dateCreated: '2014-02-03', isAdmin: true, sabuk: "biru", provinsi: "jatim" },
    { id: 29, name: 'einr', rating: 3.2, country: 'japng', dateCreated: '2013-02-03', isAdmin: true, sabuk: "ungu", provinsi: "jatim" },
    { id: 30, name: 'ucok', rating: 3.2, country: 'korut', dateCreated: '2017-02-03', isAdmin: false, sabuk: "ungu", provinsi: "jatim" },
    { id: 31, name: 'jhon', rating: 3.2, country: 'korsel', dateCreated: '2018-02-03', isAdmin: false, sabuk: "hitam", provinsi: "bali" },
    { id: 32, name: 'nani', rating: 3.2, country: 'india', dateCreated: '2021-02-03', isAdmin: false, sabuk: "hitam", provinsi: "jatim" },
    { id: 33, name: 'losi', rating: 3.2, country: 'india', dateCreated: '2022-02-03', isAdmin: true, sabuk: "kuning", provinsi: "jatim" },
    { id: 34, name: 'kali', rating: 3.2, country: 'india', dateCreated: '2022-02-03', isAdmin: false, sabuk: "hijau", provinsi: "bali" },
    { id: 35, name: 'mnsa', rating: 3.2, country: 'srilanka', dateCreated: '2023-02-03', isAdmin: true, sabuk: "hijau", provinsi: "jatim" },
    { id: 36, name: 'yudi', rating: 3.2, country: 'badui', dateCreated: '2025-02-03', isAdmin: false, sabuk: "biru", provinsi: "jatim" },
    { id: 37, name: 'zamn', rating: 3.2, country: 'germany', dateCreated: '2016-02-03', isAdmin: false, sabuk: "biru", provinsi: "bali" },
    { id: 38, name: 'mawa', rating: 3.2, country: 'rusia', dateCreated: '2017-02-03', isAdmin: true, sabuk: "hijau", provinsi: "jepara" },
    { id: 39, name: 'andi', rating: 4.1, country: 'indonesia', dateCreated: '2018-06-15', isAdmin: false, sabuk: 'merah', provinsi: 'jakarta' },
    { id: 40, name: 'budi', rating: 3.5, country: 'malaysia', dateCreated: '2019-11-20', isAdmin: true, sabuk: 'kuning', provinsi: 'penang' },
    { id: 41, name: 'siti', rating: 4.7, country: 'indonesia', dateCreated: '2020-03-11', isAdmin: false, sabuk: 'hitam', provinsi: 'surabaya' },
    { id: 42, name: 'reza', rating: 3.9, country: 'singapura', dateCreated: '2021-05-09', isAdmin: true, sabuk: 'biru', provinsi: 'singapura' },
    { id: 43, name: 'maya', rating: 2.8, country: 'brunei', dateCreated: '2016-07-21', isAdmin: false, sabuk: 'putih', provinsi: 'bandar seri begawan' },
    { id: 44, name: 'agus', rating: 4.3, country: 'indonesia', dateCreated: '2019-09-30', isAdmin: true, sabuk: 'hijau', provinsi: 'semarang' },
    { id: 45, name: 'dian', rating: 3.6, country: 'thailand', dateCreated: '2022-01-17', isAdmin: false, sabuk: 'kuning', provinsi: 'bangkok' },
    { id: 46, name: 'rina', rating: 4.0, country: 'vietnam', dateCreated: '2018-12-03', isAdmin: false, sabuk: 'merah', provinsi: 'hanoi' },
    { id: 47, name: 'toni', rating: 2.9, country: 'filipina', dateCreated: '2017-04-28', isAdmin: true, sabuk: 'biru', provinsi: 'manila' },
    { id: 48, name: 'yuni', rating: 3.4, country: 'indonesia', dateCreated: '2023-08-14', isAdmin: false, sabuk: 'hijau', provinsi: 'bandung' }

    // Tambahkan lebih banyak data sesuai kebutuhan
  ];
  
  export const columns = [
    { field: 'name', headerName: 'Name', width: 150 },
    { field: 'rating', headerName: 'Rating', width: 100, type: 'number' },
    { field: 'country', headerName: 'Country', width: 150 },
    { field: 'dateCreated', headerName: 'tanggal lahir', width: 150 },
    { field: 'isAdmin', headerName: 'Is Admin', width: 100, type: 'boolean' },
    { field: 'sabuk', headerName: 'sabuk', width: 150 },
    { field: 'provinsi', headerName: 'provinsi', width: 150 }
  ];
  